load("@rules_cc//cc:defs.bzl", "cc_library")

#
# TARGETS
#

cc_library(
  name = "Parser",
  srcs = ["Parser.cpp"],
  hdrs = ["Parser.hpp"],
  visibility = [
    "//FileSystem:__pkg__",
    "//Servers:__pkg__",
  ],
)
