#
# Pkg-config
#

http_archive(
  name = "bazel_pkg_config",
  strip_prefix = "bazel_pkg_config-master",
  urls = ["https://github.com/cherrry/bazel_pkg_config/archive/master.zip"],
)

load("@bazel_pkg_config//:pkg_config.bzl", "pkg_config")

pkg_config(
  name = "gtkmm-3.0",
)


#
# GTK 3.0 SUPPORT
#

# gtk-3.0 from /usr/include
new_local_repository(
  name = "Gtk-3.0-inc",
  path = "/usr/include",
  build_file = "gtkinc.BUILD",
)
